# Generated by Django 4.2 on 2024-04-15 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coordimeetgroup_alter_member_role_alter_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordimeetgroup',
            name='group_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
