# Generated by Django 4.2 on 2024-04-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0004_auto_20220831_1500'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_coordimeetgroup_group_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordimeetgroup',
            old_name='group_uuid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='coordimeetgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='coordimeetgroup',
            name='webpush_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpush.group'),
        ),
    ]
