# Generated by Django 4.2 on 2024-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coordimeetgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordimeetuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Anonymous')], default=1),
        ),
    ]
