# Generated by Django 4.2 on 2024-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_coordimeetuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordimeetgroup',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
