# Generated by Django 4.2 on 2024-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='selected_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
