# Generated by Django 4.2 on 2024-04-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coordimeetgroup_alter_member_role_alter_member_group'),
        ('events', '0004_alter_event_organiser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnotification',
            name='notification_text',
        ),
        migrations.AddField(
            model_name='event',
            name='invited_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_group_events', to='users.coordimeetgroup'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='availability_level',
            field=models.IntegerField(choices=[(1, 'If need be'), (2, 'Maybe available'), (3, 'Available')], default=3),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='not_comming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Group')], default=1),
        ),
        migrations.DeleteModel(
            name='EventParticipantAvailability',
        ),
    ]
