# Generated by Django 4.2 on 2024-05-06 19:47

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventnotification_notification_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventNotification',
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.IntegerField(choices=[(1, 'After creation'), (2, 'After update'), (3, 'Before deadline'), (4, 'After event date selected'), (5, 'Before event starts')])),
                ('notification_time', models.DateTimeField(null=True, blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='events.event')),
            ],
        ),
    ]
