# Generated by Django 4.2 on 2024-06-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventnotification_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='availability_level',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='user_uuid',
        ),
    ]
