# Generated by Django 4.2 on 2024-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organiser_group',
        ),
        migrations.AddField(
            model_name='event',
            name='is_group_organiser',
            field=models.BooleanField(default=False),
        ),
    ]
