# Generated by Django 4.2.27 on 2026-01-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_anonymous_email_coordimeetuser_anonymous_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordimeetFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to='users.coordimeetuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from', to='users.coordimeetuser')),
            ],
        ),
    ]
