# Generated by Django 4.2.27 on 2026-01-02 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.IntegerField(choices=[(1, 'After creation'), (2, 'After update'), (3, 'Before deadline'), (4, 'After event date selected'), (5, 'Before event starts'), (6, 'At the deadline'), (7, 'Automatically finish event')])),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'notification_type')},
            },
        ),
    ]
