# Generated by Django 4.2.27 on 2026-01-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordimeetuser',
            old_name='anonymous_email',
            new_name='anonymous_username',
        ),
    ]
