# Generated by Django 4.2.27 on 2026-01-02 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used to generate the invite link', unique=True)),
                ('event_calendar_type', models.IntegerField(choices=[(1, 'Date'), (2, 'Date and hour')], default=2)),
                ('event_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Group'), (3, 'Closed')], default=1)),
                ('is_group_organiser', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_length', models.IntegerField(help_text='Event length in units based on the event_calendar_type')),
                ('deadline', models.DateTimeField()),
                ('selected_start_date', models.DateTimeField(blank=True, null=True)),
                ('selected_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_group_events', to='users.coordimeetgroup')),
                ('organiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organiser_events', to='users.coordimeetuser')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_comming', models.BooleanField(default=False)),
                ('coordimeet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='users.coordimeetuser')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_availabilities', to='events.eventparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='EventAvailabilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_availability_options', to='events.event')),
            ],
        ),
    ]
