# Generated by Django 4.2.27 on 2026-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_thread_message_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of email Message-IDs for threading emails in this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_method',
            field=models.IntegerField(choices=[(1, 'Push notifications'), (2, 'Email'), (3, 'Both')], default=1, help_text='Method to use for sending event notifications'),
        ),
    ]
